default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: marcelo
  password: ka258tem

development:
  <<: *default
  database: sisgo_development

test:
  <<: *default
  database: sisgo_test

production:
  <<: *default
  database: sisgo_production
